// styling/global-styles.js
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff", padding: 16 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  form: { width: "80%", maxWidth: 420, alignSelf: "center" },
  title: { fontSize: 22, fontWeight: "600", marginBottom: 16, textAlign: "center" },
  hero: { fontSize: 28, fontWeight: "700", marginBottom: 4 },
  subtitle: { fontSize: 16, color: "#666", textAlign: "center" },
  formStatus: { textAlign: "center", color: "#555", marginTop: 8 },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  button: {
    backgroundColor: "#000",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    marginVertical: 6,
  },
  authActionRow: { flexDirection: "row", justifyContent: "space-between" },
  authActionButton: { flex: 1, marginHorizontal: 4 },
  buttonLabel: { color: "#fff", fontWeight: "600", fontSize: 16 },
  buttonDisabled: { backgroundColor: "#ccc", opacity: 0.7 },
  buttonAlt: { backgroundColor: "#4B9CD3", marginLeft: 8 },
  buttonMuted: { backgroundColor: "#888" },
  linkButton: { alignSelf: "center", marginTop: 8 },
  linkButtonLabel: { color: "#007AFF", fontWeight: "600" },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  headerTitle: { fontSize: 22, fontWeight: "bold" },
  browseButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#4B9CD3",
    borderRadius: 8,
  },
  browseText: { color: "#fff", fontWeight: "600" },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 18, fontWeight: "600", marginBottom: 8 },
  bookCard: { width: 140, alignItems: "center", marginRight: 12 },
  bookCover: { width: 120, height: 170, borderRadius: 8, marginBottom: 6 },
  bookTitle: { fontSize: 13, textAlign: "center" },
  recommendationsGrid: { flexDirection: "row", flexWrap: "wrap" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalContainer: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
  },
  modalImage: {
    width: 160,
    height: 220,
    borderRadius: 8,
    alignSelf: "center",
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 4,
  },
  modalAuthor: {
    fontSize: 16,
    fontWeight: "500",
    color: "#666",
    textAlign: "center",
    marginBottom: 12,
  },
  modalBlurb: {
    fontSize: 14,
    color: "#444",
    textAlign: "center",
    marginBottom: 12,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },

  searchHeaderContainer: {
    backgroundColor: "#f2f2f2",
    padding: 16,
    borderRadius: 12,
    marginTop: 12,
  },
  searchHeaderText: { fontSize: 16, fontWeight: "600", marginBottom: 8 },
  searchInput: {
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },

  tabRow: { flexDirection: "row", marginBottom: 12 },
  tabButton: {
    flex: 1,
    padding: 10,
    backgroundColor: "#ddd",
    borderRadius: 8,
    marginRight: 4,
  },
  tabButtonActive: { backgroundColor: "#000" },
  tabButtonLabel: {
    textAlign: "center",
    color: "#000",
    fontWeight: "600",
  },
  tabButtonLabelActive: { color: "#fff" },
  libraryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingBottom: 16,
  },
  createListButton: { marginBottom: 12 },
  modalScroll: { maxHeight: 300, marginBottom: 12 },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    padding: 6,
    borderRadius: 6,
  },
  listItemSelected: { backgroundColor: "#cce5ff" },
  listItemImage: { width: 40, height: 60, marginRight: 8, borderRadius: 6 },

  groupCard: {
    backgroundColor: "#f9f9f9",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  groupName: { fontSize: 18, fontWeight: "600", marginBottom: 4 },
  groupBook: { color: "#555" },
  groupsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  groupButton: { alignSelf: "center", marginTop: 8, paddingHorizontal: 20 },
  switchRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  switchLabel: { marginRight: 8 },
  modalButton: { flex: 1, marginHorizontal: 6 },

  searchScroll: { paddingBottom: 20 },
  searchHeaderTall: { minHeight: 140 },
  searchRow: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  searchInputFlex: { flex: 1, marginRight: 10 },
  searchButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  searchButtonText: { color: "#fff", fontWeight: "600" },
  searchResults: { marginTop: 20 },
  searchActiveFilter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  searchActiveLabel: { fontWeight: "600" },
  searchClearButton: { paddingHorizontal: 8, paddingVertical: 4 },
  searchClearText: { color: "#007AFF", fontWeight: "600" },
  searchResultCard: {
    padding: 12,
    marginBottom: 10,
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  searchResultTitle: { fontWeight: "600", fontSize: 16 },
  searchResultAuthor: { color: "#555", marginTop: 4 },
  searchResultSummary: { color: "#444", marginTop: 6, fontSize: 14 },
  searchResultMeta: { color: "#666", marginTop: 6, fontSize: 12 },
  searchResultButton: { marginTop: 10 },
  searchEmpty: { textAlign: "center", marginTop: 20, color: "#777" },
  genreGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 20,
  },
  genreCard: {
    flexBasis: "32%",
    marginBottom: 10,
    height: 70,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  genreLabel: { fontWeight: "600", textAlign: "center", fontSize: 14 },
  genreCardActive: { borderColor: "#000", backgroundColor: "#e8f0ff" },
});
